version: '3.8'

services:
  db:
    image: mysql:5.7
    volumes:
      - db-data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: r00tp@ss%ord
      MYSQL_DATABASE: weather_app
      MYSQL_USER: root
    ports:
      - "3306:3306"
    networks:
      - backend-net

  backend:
    build: ./backend
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "5000:5000"
    restart: always
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
      DATABASE_URL: mysql://weather_user:r00tp@ss%ord@db/weather_app
    depends_on:
      - db
    networks:
      - backend-net

  frontend:
    image: nginx:latest
    volumes:
      - ./frontend:/usr/share/nginx/html:ro
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend
    networks:
      - backend-net

networks:
  backend-net:
    driver: bridge

volumes:
  db-data: