---
all:
  children:
    web_servers:
      hosts:
        13.93.162.176:
      vars:
        ansible_ssh_private_key_file: /home/tsrlearning/.ssh/tsrlearningkey

    php_servers:
      hosts:
        13.93.162.121:
      vars:
        ansible_ssh_private_key_file: /home/tsrlearning/.ssh/tsrlearningkey

    database:
      hosts:
        52.160.108.143:
      vars:
        ansible_ssh_private_key_file: /home/tsrlearning/.ssh/tsrlearningkey

# Nested Groups
    Production:
      children:
        php_servers:

    Development:
      children:
        web_servers:

    Dba:
      children:
        database: