---
all:
  children:
    web_servers:
      hosts:
        13.88.183.163:
      vars:
        ansible_ssh_host_key_checking: no
        ansible_ssh_private_key_file: /home/tsrlearning/.ssh/tsrlearningkey

    php_servers:
      hosts:
        13.93.167.167:
      vars:
        ansible_ssh_host_key_checking: no
        ansible_ssh_private_key_file: /home/tsrlearning/.ssh/tsrlearningkey

    database:
      hosts:
        52.160.106.48:
      vars:
        ansible_ssh_host_key_checking: no
        ansible_ssh_private_key_file: /home/tsrlearning/.ssh/tsrlearningkey

# Nested Groups
    Production:
      children:
        php_servers:

    Development:
      children:
        web_servers:

    Dba:
      children:
        database: