---
- name: Create GitHub Repository
  hosts: localhost
  gather_facts: no
  vars_files:
    - variables/secrets.yml
  tasks:
    # - name: Generate JSON body from Jinja2 template
    #   set_fact:
    #     repo_body: "{{ lookup('template', 'github_repo_body.j2') }}"

    - name: Create GitHub Repository
      uri:
        url: "{{ github_api_url }}"
        method: POST
        # body: "{{ repo_body }}"
        body_format: json
        body:
          name: "{{ repo_name }}"
          description: "{{ repo_description }}"
          private: "{{ repo_private }}"
          auto_init: true
        headers:
          Authorization: "token {{ github_token }}"
          Content-Type: "application/json"
        status_code: 201
      register: response

    - name: Print API Response
      debug:
        var: response.json

    - name: Delete Repository
      uri:
        url: "{{ delete_github_url }}"
        method: DELETE
        headers:
          Authorization: "token {{ github_token }}"
          Accept: "application/vnd.github+json"
        status_code: 204
      register: reponse_delete

    - name: Print API Response
      debug:
        var: reponse_delete.status

    - name: List public Repositorys
      uri:
        url: "{{ list_github_url }}"
        method: GET
        headers:
          Authorization: "token {{ github_token }}"
          Accept: "application/vnd.github+json"
        status_code: 200
      register: repos_list_reponse

    - name: Print list of Repository's full names
      debug:
        msg: "{{ repos_list_reponse.json | map(attribute='full_name') | list }}"

    - name: Print list of Repository's full names
      debug:
        msg: "{{ (repos_list_reponse.json | map(attribute='full_name') | list)[2] }}"

    - name: Print list of Repository's names
      debug:
        msg: "{{ repos_list_reponse.json | map(attribute='name') | list }}"

    - name: Print list of Repository's names
      debug:
        msg: "{{ (repos_list_reponse.json | map(attribute='name') | list)[0] }}"      
