    github_token: "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"
    repo_name: "test-repo"
    repo_description: "Created via Ansible"
    repo_private: false
    repo_owner: tsrlearning-training
    github_api_url: "https://api.github.com/orgs/tsrlearning-training/repos"