version: '3.8'
services:
  web:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/booking.html:/usr/share/nginx/html/booking.html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

    depends_on:
      - db

  db:
    build: ./mysql
    environment:
      MYSQL_DATABASE: 'InventoryDB'
      MYSQL_USER: 'tsrlearning'
      MYSQL_PASSWORD: 'tsrlearning'
      MYSQL_ROOT_PASSWORD: 'tsrlearning'
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql

volumes:
  db_data:
