version: '3.8'
services:
  web:
    build: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./site:/usr/share/nginx/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/fastcgi-php.conf:/etc/nginx/snippets/

    depends_on:
      - db
    networks:
      - app-network

  php:
    image: php:7.4-fpm
    expose:
      - "9000:9000"
    volumes:
      - ./site:/var/www/html
    networks:
      - app-network
  db:
    build: ./mysql
    environment:
      MYSQL_DATABASE: 'InventoryDB'
      MYSQL_USER: 'tsrlearning'
      MYSQL_PASSWORD: 'tsrlearning'
      MYSQL_ROOT_PASSWORD: 'tsrlearning'
    ports:
      - "3306:3306"
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
networks:
  app-network:
    driver: bridge

volumes:
  db_data:
