---
# tasks file for docker

- name: Update OS
  apt: 
    update_cache: yes
    state: latest

- name: Install Cert. and Curl
  apt:
    name: "{{ item }}"
    state: latest
  loop:
    - ca-certificates 
    - curl

- name: Chmod /etc/apt/keyrings and make sure directory exists
  file:
    path: "{{ docker_keyring }}"
    state: directory
    mode: "0755"

- name: Add Docker GPG Key 
  get_url: 
    url: "{{ docker_url }}"
    dest: "{{ key_dest }}"
    mode: "0644"

- name: Add the repository to Apt sources
  shell: |
    echo "deb [arch=$(dpkg --print-architecture) signed-by={{ key_dest }}] https://download.docker.com/linux/ubuntu $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
  args:
    executable: /bin/bash

- name: Install the Docker packages
  apt:
    update_cache: true
    state: present
    name: "{{ item }}"
  loop:
    - docker-ce 
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin