name: Scheduled Azure Cost Monitoring

on:
  push:
    branches:
      - 'tsrlearningdev'
      - 'monitor_cost.yml'
  # schedule:
    # - cron: '0 0 * * *' # This runs the workflow daily at midnight UTC

env:
  # AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  # AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
  # AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  # TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
   TF_VAR_client_secret: "${{ secrets.client_secret }}"

jobs:
  Monitor-Azure-Cost:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Az login
        run: az login --use-device-code

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Run cost monitoring script
        run: |
          chmod +x ./monitor_cost.sh
          ./monitor_cost.sh "$AZURE_CLIENT_ID=b26145ad-4bdc-4af7-bc86-8dc3d89e9d4e" "$AZURE_CLIENT_SECRET=${{ secrets.client_secret }}" "$AZURE_TENANT_ID=389dc11c-508a-4f1e-a529-1f19aa1a8e7b"

        env:
        #   AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
        #   AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
        #   AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
        #   TEAMS_WEBHOOK_URL: ${{ secrets.TEAMS_WEBHOOK_URL }}
         TF_VAR_client_secret: "${{ secrets.client_secret }}"
